# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3a0665bf8b449f4ee37af7eb5304e5152c652bdd8492603e6e223bdb210c2030d8757cd5875a3b52d1e0015e7e37f77c1d5e859ede12ce040d29a355e0bd9b92

test:
  secret_key_base: 69ed95509b3cba9fca4939a01556d1a03373a97f332d6d25347bd6eca5a71fb432a7447c2f24b7786db196111f8358a1b76d15cb5ec2ab7f16d8405dd29b9d93

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
